server:
  port: 8083

spring:
  application:
    name: my-report
  data:
    mongodb:
      host: app_db
      port: 27017
      database: my-report

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://my-service-discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
